Repository devinit/ddw-analyst-ui, pull requests merged in 2019-05, with the labels that each got.

#87 Much faster estimated count
  core/models.py
  core/pypika_utils.py
  core/serializers.py
Labels: Backend, complete

#89 Meta edits
  data/tests.py
  data_updates/manual/CSV/meta.csv
Labels: complete

#90 Multiconcat backend
  core/pypika_utils.py
Labels: complete

#86 Feature/append isos
  data_updates/R/fts.R
  data_updates/manual/CSV/meta_columns.csv
Labels: complete

#94 Don't drop Namibia ISO2
  data_updates/Python/manual_data.py
Labels: complete

#91 Fix/psycopg2 memleak
  core/models.py
  core/urls.py
  core/views.py
  data/db_manager.py
  frontend/src/pages/QueryData/QueryData.tsx
  frontend/src/utils/api.ts
Labels: Backend, In Progress, enhancement

#99 10 minute timeout
  Dockerfile
  config/nginx/django.conf
Labels: complete

#100 Feature/test queries
  core/fixtures/test_data.json
  core/tests.py
  data/db_router.py
  data/models.py
  data/test_migrations/0001_initial.py
  data/test_migrations/__init__.py
  data/tests.py
  database_setup/sql_load.sql
  ddw_analyst_ui/docker_test_settings.py
  ddw_analyst_ui/settings.py
  ddw_analyst_ui/test_settings.py
  package.json
Labels: Backend, complete

#101 Err handling db manager
  core/serializers.py
  data/db_manager.py
  data/tests.py
Labels: Backend, complete

#108 New NullIf function to avoid division by zero.
  core/pypika_utils.py
  data/tests.py
Labels: complete

#111 Data updates
  data_updates/R/fts.R
  data_updates/manual/CSV/di_deflators_2017.csv
  data_updates/manual/CSV/meta.csv
  data_updates/manual/CSV/meta_columns.csv
  data_updates/manual/CSV/non_grant_revenue.csv
Labels: complete

#117 Patch/1.0.2
  frontend/src/components/FilterQueryBuilder/FilterQueryBuilder.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/SidebarFooter/SidebarFooter.tsx
  frontend/src/components/SidebarFooter/index.ts
  frontend/src/layouts/MainLayout.tsx
  frontend/src/styles/main.scss
  frontend/static/frontend/assets/images/logo.png
  package-lock.json
  package.json
Labels: Frontend, Review Required

#115 Feature/ssl
  .gitignore
  config/nginx/django.conf
  core/tests.py
  ddw_analyst_ui/settings.py
  docker-compose.yml
Labels: Backend, complete, enhancement

#124 Feature/password change backend
  README.md
  core/tests.py
  core/urls.py
  core/views.py
  frontend/src/actions/modal.ts
  frontend/src/components/AccountModal/AccountModal.tsx
  frontend/src/components/AccountModal/index.ts
  frontend/src/components/ChangePasswordForm/ChangePasswordForm.tsx
  frontend/src/components/ChangePasswordForm/index.ts
  frontend/src/layouts/MainLayout.tsx
  frontend/src/reducers/modal.ts
  frontend/src/store/index.ts
  frontend/src/utils/api.ts
Labels: Backend, complete

#118 Feature/auto update meta
  core/fixtures/test_data.json
  core/migrations/0012_auto_20190523_1623.py
  core/models.py
  core/serializers.py
  data/management/commands/load_manual.py
  data/management/commands/update_meta.py
  data/tests.py
  data_updates/completed_scripts.sh
  data_updates/fts.sh
  data_updates/indexing.sh
  data_updates/oecd.sh
  data_updates/povcalnet.sh
  data_updates/wdi.sh
  data_updates/weo.sh
  database_setup/sql_load.sql
Labels: Backend, complete
